trigger:
  branches:
    include:
      - develop

pool:
  vmImage: 'ubuntu-24.04'

steps:
  - checkout: self

  - task: UseNode@1
    inputs:
      version: '22.x'

  - script: |
      curl -fsSL https://bun.sh/install | bash
    displayName: 'Install Bun'

  - script: echo "##vso[task.setvariable variable=PATH]$(HOME)/.bun/bin:$(PATH)"
    displayName: 'Add Bun to PATH'

  - script: bun install
    displayName: 'Install dependencies with Bun'

  - script: bun run test
    displayName: 'Run tests with Bun'
    workingDirectory: apps/backend
    env:
      CI: true
