trigger:
  branches:
    include:
      - id/73/fixPipelineTest

pool:
  vmImage: 'ubuntu-latest'

variables:
  CI_DATABASE_URL: 'postgres://postgres:postgres@127.0.0.1:5432/main'

services:
  postgres:
    image: postgres:17.4-alpine
    ports:
      - 5432:5432
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    options: >-
      --health-cmd="pg_isready"
      --health-interval=10s
      --health-timeout=5s
      --health-retries=5

steps:
  - checkout: self

  - task: UseNode@1
    inputs:
      version: '22.x'

  - script: |
      curl -fsSL https://bun.sh/install | bash
    displayName: 'Install Bun'

  - script: echo "##vso[task.setvariable variable=PATH]$(HOME)/.bun/bin:$(PATH)"
    displayName: 'Add Bun to PATH'

  - script: bun install
    displayName: 'Install dependencies with Bun'

  - script: bun run test
    displayName: 'Run tests with Bun'
    workingDirectory: apps/backend
    env:
      CI: true
      NEON_CONNECTION_STRING: $(CI_DATABASE_URL)
