// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  Bindings: {
    NEON_CONNECTION_STRING: string;
    NEO4J_URL: string;
    NEO4J_USER: string;
    NEO4J_PASSWORD: string;
  };
}
