trigger:
  branches:
    include:
      - id/77/fixPipeline

jobs:
  - job: bdd_test
    displayName: 'Run BDD E2E tests'
    pool:
      vmImage: 'ubuntu-latest'

    services:
      postgres:
        image: postgres:17.4-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: main
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - checkout: self

      - script: |
          echo "127.0.0.1 db.localtest.me" | sudo tee -a /etc/hosts
        displayName: "Add db.localtest.me to /etc/hosts"

      - script: |
          echo "Waiting for PostgreSQL..."
          for i in {1..20}; do
            if PGPASSWORD=postgres psql -h db.localtest.me -U postgres -d main -c "SELECT 1" &>/dev/null; then
              echo "PostgreSQL is ready"
              break
            fi
            sleep 2
          done
        displayName: 'Wait for rdb server to start'

      - script: |
          echo "Waiting  before starting Neon Proxy..."
          sleep 20
          # ログファイルパスを定義
          LOG_DIR=$(pwd)/neon-proxy-logs
          mkdir -p $LOG_DIR

          echo "Starting Neon Proxy..."
          docker run -d --name neon-proxy \
            -e PG_CONNECTION_STRING=postgres://postgres:postgres@db.localtest.me:5432/main \
            -p 4444:4444 \
            ghcr.io/timowilhelm/local-neon-http-proxy:main

          # バックグラウンドでログ収集を開始
          docker logs -f neon-proxy > $LOG_DIR/neon-proxy.log 2>&1 &
          LOGGER_PID=$!
          echo $LOGGER_PID > $LOG_DIR/neon.pid

          # Proxy が立ち上がるまで待機
          echo "Waiting for Neon Proxy..."
          for i in {1..20}; do
            if curl -s http://db.localtest.me:4444/sql &>/dev/null; then
              echo "Neon Proxy is ready"
              break
            fi
            sleep 2
          done
        displayName: 'Start Neon Proxy'

      - task: UseNode@1
        inputs:
          version: '22.x'

      - script: |
          curl -fsSL https://bun.sh/install | bash
        displayName: 'Install Bun'

      - script: echo "##vso[task.setvariable variable=PATH]$(HOME)/.bun/bin:$(PATH)"
        displayName: 'Add Bun to PATH'

      - script: bun install
        displayName: 'Install Dependencies'

      - script: npx playwright install --with-deps chromium
        workingDirectory: apps/frontend
        displayName: 'download new browsers'

      - script: cp .dev.vars.ci .dev.vars
        workingDirectory: apps/backend
        displayName: 'Setting Backend env vars'

      - script: cp .env.sample .dev.local
        workingDirectory: apps/frontend
        displayName: 'Setting Frontend env vars'

      - script: |
          bun run dev > backend.log 2>&1 &
          echo $! > ../backend.pid
        workingDirectory: apps/backend
        displayName: 'Start Backend'

      - script: |
          bun run preview:ci > frontend.log 2>&1 &
          echo $! > ../frontend.pid
        workingDirectory: apps/frontend
        displayName: 'Start Frontend'

      # 🕐 Backend / Frontend の起動待ち（適宜 curl でチェック）
      - script: |
          echo "Waiting for frontend server..."
          for i in {1..20}; do
            if curl -s http://localhost:5173 > /dev/null; then
              echo "Frontend server is up."
              break
            fi
            sleep 2
          done

          echo "Waiting for backend server..."
          for i in {1..20}; do
            if curl -s http://localhost:8787 > /dev/null; then
              echo "Backend server is up."
              break
            fi
            sleep 2
          done
        displayName: 'Wait for servers to start'

      - script: bun run migrate:ci
        workingDirectory: packages/database
        displayName: 'Migration RDB'

      - script: bun run bdd-test
        workingDirectory: packages/bdd-e2e-test
        displayName: 'Run E2E Tests'
        env:
          CI: true

      - task: PublishBuildArtifacts@1
        condition: always()
        inputs:
          pathToPublish: 'packages/bdd-e2e-test/output'
          artifactName: 'e2e-output'
        displayName: 'Upload screenshots as artifacts'

      - task: PublishBuildArtifacts@1
        condition: always()
        inputs:
          pathToPublish: 'apps/backend/backend.log'
          artifactName: 'backend-log'
        displayName: 'Upload screenshots as artifacts'

      # Neon Proxyログをアーティファクトとして保存するためのタスク
      - task: PublishBuildArtifacts@1
        condition: always()
        inputs:
          pathToPublish: 'neon-proxy-logs'
          artifactName: 'neon-proxy-logs'
        displayName: 'Upload Neon Proxy logs as artifacts'

      - script: |
          kill $(cat backend.pid)
          kill $(cat frontend.pid)
          docker stop neon-proxy
          docker rm neon-proxy
        displayName: 'Cleanup Servers'
        workingDirectory: apps
        condition: always()

      - script: kill $(cat neon.pid)
        displayName: 'Cleanup Neon Proxy logs'
        workingDirectory: neon-proxy-logs
        condition: always()
