trigger:
  branches:
    include:
      - id/75/bddOnPipeline

jobs:
  - job: bdd_test
    displayName: 'Run BDD E2E tests'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      CI_DATABASE_URL: 'postgres://postgres:postgres@127.0.0.1:5432/main'

    services:
      postgres:
        image: postgres:17.4-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: main
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      firebase: firebase
    steps:
      - checkout: self
      # デバッグ用ステップ追加
      - script: |
          echo "Checking firebase_isready script..."
          docker exec -i $(docker ps -q --filter name=firebase) which firebase_isready || echo "Script not found"
          docker exec -i $(docker ps -q --filter name=firebase) ls -la /usr/local/bin/firebase_isready || echo "No access rights"
          docker exec -i $(docker ps -q --filter name=firebase) bash -c "firebase_isready || echo Exit code: $?"
        displayName: 'Debug firebase_isready'
        condition: always()  # 常に実行
      - task: UseNode@1
        inputs:
          version: '22.x'

      - script: |
          curl -fsSL https://bun.sh/install | bash
        displayName: 'Install Bun'

      - script: echo "##vso[task.setvariable variable=PATH]$(HOME)/.bun/bin:$(PATH)"
        displayName: 'Add Bun to PATH'

      - script: bun install
        displayName: 'Install Dependencies'

      - script: npx playwright install   
        workingDirectory: apps/frontend
        displayName: 'download new browsers'

      - script: cp .dev.vars.ci .dev.vars
        workingDirectory: apps/backend
        displayName: 'Setting Backend env vars'

      - script: cp .env.sample .dev.local
        workingDirectory: apps/frontend
        displayName: 'Setting Frontend env vars'

      - script: |
          bun run dev &
          echo $! > backend.pid
        workingDirectory: apps/backend
        displayName: 'Start Backend'

      - script: |
          bun run dev:ci  &
          echo $! > frontend.pid
        workingDirectory: apps/frontend
        displayName: 'Start Frontend'

      # 🕐 Backend / Frontend の起動待ち（適宜 curl でチェック）
      - script: |
          echo "Waiting for frontend server..."
          for i in {1..20}; do
            if curl -s http://localhost:5173 > /dev/null; then
              echo "Frontend server is up."
              break
            fi
            sleep 2
          done

        displayName: 'Wait for servers to start'

      - script: bun run migrate:ci
        workingDirectory: packages/database
        displayName: 'Migration RDB'

      - script: bun run bdd-test
        workingDirectory: packages/bdd-e2e-test
        displayName: 'Run E2E Tests'
        env:
          CI: true

      - task: PublishBuildArtifacts@1
        condition: always()
        inputs:
          pathToPublish: 'packages/bdd-e2e-test/output'
          artifactName: 'e2e-output'
        displayName: 'Upload screenshots as artifacts'

      - script: |
          kill $(cat backend.pid)
          kill $(cat frontend.pid)
        displayName: 'Cleanup Servers'
        condition: always()
