openapi: "3.1.0"
info:
  title: "Odyssage API"
  description: "Odyssage Backend API"
  version: "0.0.0"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
servers:
  - url: "http://127.0.0.1:8787"
    description: "Local Server"
paths:
  /api/scenarios:
    $ref: './paths/scenarios.yaml'
  /api/scenarios/public:
    $ref: './paths/scenariosPublic.yaml'
  /api/scenario/{id}:
    $ref: './paths/scenario.yaml'
  /api/users/{uid}: 
    $ref: './paths/user.yaml'
  /api/users/{uid}/scenario:
    $ref: './paths/userScenario.yaml'
  /api/users/{uid}/stocked-scenarios:
    $ref: './paths/userScenarioStocks.yaml'
  /api/users/{uid}/stocked-scenarios/{scenario_id}:
    $ref: './paths/userScenarioStockItem.yaml'
  /api/sessions:
    $ref: './paths/sessions.yaml'
  /api/sessions/{id}:
    $ref: './paths/session.yaml'
  /api/sessions/gm/{gm_id}:
    $ref: './paths/sessionsByGm.yaml'

components:
  schemas: {}
  responses:
    $ref: './components/schemas/response.yaml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
