services:
  schemaspy:
    build:
      context: .
      dockerfile: ../schemaspy/Dockerfile.dev
    container_name: schemaspy
    image: schemaspy/schemaspy
    volumes:
      - ../astro/public/odyssage-dbdoc:/schemaspy_output
      - ./schemaspy/schemaspy.properties:/schemaspy.properties
    command: "java -jar schemaspy.jar -vizjs"

