name: E2E Tests

on:
  push:
    branches:
      - develop
      - docs
    paths:
      - apps/backend/**
      - apps/frontend/**
      - packages/bdd-e2e-test/**
      - packages/database/**
      - packages/schema/**
      - .github/workflows/e2e-tests.yml
      - .github/workflows/reusable/e2e-test.yml
  workflow_dispatch:

jobs:
  run-e2e-tests:
    uses: ./.github/workflows/reusable/e2e-test.yml
    # テスト結果のステータスが取得できます
    # outputs:
    #   test_status: ${{ jobs.run-e2e-tests.outputs.test_status }}
