name: Deploy Documents to Pages

on:
  push:
    branches:
      - develop
      - docs
    paths:
      - .github/workflows/**
      - docs/**
      - tests/**
      - src/**/tests/**
      - stories/**
  workflow_dispatch:
    
permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: 'pages'
  cancel-in-progress: false
  
jobs:
  # E2Eテストを実行
  e2e-tests:
    uses: ./.github/workflows/reusable-e2e-test.yml
  
  # ドキュメントを生成
  build-docs:
    needs: e2e-tests
    uses: ./.github/workflows/reusable-build-docs.yml
    with:
      build_path: ./docs/astro
  
  # GitHub Pagesにデプロイ
  deploy-pages:
    needs: build-docs
    uses: ./.github/workflows/reusable-deploy-pages.yml
